# Site settings
title: Joe Hobson
email: hello@joe-hobson.com
description: "Portfolio and blog for Joe Hobson, Front-End Developer"
baseurl: ""
url: "http://joe-hobson.com"
twitter_username: hobbageking
github_username:  fant0mex

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed
