# Site settings
title: Joe Hobson
email: joseph.j.hobson@gmail.com
description: "Portfolio and blog for Joe Hobson, Front-End Developer"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: hobbageking
github_username:  fant0mex

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed