# Site settings
title: Joe Hobson
email: joseph.j.hobson@gmail.com
description: "Portfolio and blog for Joe Hobson, Front-End Developer"
baseurl: "/portfolio/"
url: "http://fant0mex.github.io/portfolio/"
twitter_username: hobbageking
github_username:  fant0mex

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: :compressed